name: "e2e-k8s-incluster-lvmd"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
  push:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
    branches:
      - "main"
jobs:
  e2e-k8s-incluster-lvmd:
    name: "e2e-k8s-incluster-lvmd"
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        kubernetes_versions: ["1.31.0", "1.30.4", "1.29.8"]
        test_lvmd_type: ["daemonset", "embedded"]
    env:
      KUBERNETES_VERSION: ${{ matrix.kubernetes_versions }}
      TEST_LVMD_TYPE: ${{ matrix.test_lvmd_type }}
      TEST_SCHEDULER_EXTENDER_TYPE: "none"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: cache e2e sidecar binaries
        uses: actions/cache@v4
        with:
          path: |
            test/e2e/tmpbin
          key: e2e-sidecars-${{ hashFiles('csi-sidecars.mk', 'versions.mk') }}
          restore-keys: |
            e2e-sidecars-
      - run: make -C test/e2e incluster-lvmd/create-vg
      - run: make -C test/e2e incluster-lvmd/setup-minikube
      - run: make -C test/e2e incluster-lvmd/launch-minikube
      - run: make -C test/e2e incluster-lvmd/test
